name: Build and deploy extension to Bazaar
on:
  workflow_dispatch:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build and Publish Extension in BlueOS CLoud
        uses: bluerobotics/blueos-cloud-action@0.0.1
        with:
          BCLOUD_PAT: ${{secrets.BCLOUD_PAT}}
          PLATFORMS: linux/arm/v7,linux/arm64,linux/amd64
          EXTENSION: c2e1be11-d8cf-4fd9-beb0-2d4cf0926653
